# Generated by Django 6.0.2 on 2026-02-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='atracaoes',
            field=models.ManyToManyField(to='atracoes.atracao'),
        ),
    ]
